version: '3.8'

# PREENCHER AS VARIÁVEIS DA API E DO POSTGRES COM AS INFORMAÇÕES CORRETAS PARA O AMBIENTE DE DESENVOLVIMENTO
services:
  postgres:
    image: postgres:13
    container_name: 
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    ports:
      - ":"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: SmartSocialHubServer.API/Dockerfile
    container_name: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=;Port=;Database=;Username=;Password=
      - Jwt__Key=sua-chave-secreta-aqui
      - Jwt__Issuer=SmartSocialHubIssuer
      - Jwt__Audience=SmartSocialHubAudience
    ports:
      - ":" 
    depends_on:
      - postgres

volumes:
  postgres_data:
