<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartSocialHubServer.Domain\SmartSocialHubServer.Domain.csproj" />
    <ProjectReference Include="..\SmartSocialHubServer.Infrastructure\SmartSocialHubServer.Infrastructure.csproj" />
  </ItemGroup>

</Project>
